//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace security_web_filter
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizedDomain
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string NetBIOS { get; set; }
        public string UPN { get; set; }
    }
}
