//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace security_web_filter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCode
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string SipUri { get; set; }
        public string AccessCode { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Notified { get; set; }
        public Nullable<bool> PromptUser { get; set; }
    }
}
