//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace security_web_filter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public byte[] RowVersion { get; set; }
        public int Id { get; set; }
        public string Filter { get; set; }
        public string ProtectedService { get; set; }
        public string Device { get; set; }
        public string Username { get; set; }
        public string IP { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Status { get; set; }
        public int FailedLoginCount { get; set; }
        public bool Notified { get; set; }
    }
}
