//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace security_web_filter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SecurityFilterManagerEntities : DbContext
    {
        public SecurityFilterManagerEntities()
            : base("name=SecurityFilterManagerEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AccountLockout> AccountLockouts { get; set; }
        public virtual DbSet<AuthorizedDomain> AuthorizedDomains { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<SecurityFilterSetting> SecurityFilterSettings { get; set; }
        public virtual DbSet<UserDeviceAffinity> UserDeviceAffinities { get; set; }
        public virtual DbSet<DeviceCode> DeviceCodes { get; set; }
    }
}