//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace security_web_filter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityFilterSetting
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int Count { get; set; }
        public int Period { get; set; }
        public bool WhiteList { get; set; }
        public bool BlockNTLM { get; set; }
        public bool EnforceDeviceAuthorization { get; set; }
        public string InternalNetworkSubnets { get; set; }
    }
}
